# Generated by Django 2.1.5 on 2019-01-17 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('release_time', models.DateTimeField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Car')),
            ],
        ),
    ]
